# Generated by Django 4.0.4 on 2022-04-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_orderitem_name_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tex_price',
            new_name='tax_price',
        ),
    ]
