# Generated by Django 4.0.4 on 2022-04-22 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_tex_price_order_tax_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 22, 22, 23, 7, 417297)),
            preserve_default=False,
        ),
    ]
