# Generated by Django 4.0.2 on 2022-03-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_category_parent_category_category_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('categories', models.ManyToManyField(to='store.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='book',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
            preserve_default=False,
        ),
    ]
